[tool.black]
line-length = 88
[tool.isort]
line_length = 88
profile = "black"
[tool.pylint.master]
disable = [
  "duplicate-code",
  "invalid-name",
  "missing-docstring",
  "unused-argument"
]
max-line-length = 88
